"""Add detailed classification fields to pages

Revision ID: 0f19e78be270
Revises: f3g4h5i6j7k8
Create Date: 2026-01-21 05:33:54.446096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f19e78be270'
down_revision: Union[str, Sequence[str], None] = 'f3g4h5i6j7k8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classification_history_created_at', table_name='classification_history')
    op.drop_index('ix_classification_history_provider_model', table_name='classification_history')
    op.drop_index('ix_classification_history_status', table_name='classification_history')
    op.add_column('pages', sa.Column('discipline', sa.String(length=100), nullable=True))
    op.add_column('pages', sa.Column('discipline_confidence', sa.Float(), nullable=True))
    op.add_column('pages', sa.Column('page_type', sa.String(length=100), nullable=True))
    op.add_column('pages', sa.Column('page_type_confidence', sa.Float(), nullable=True))
    op.add_column('pages', sa.Column('concrete_elements', sa.JSON(), nullable=True))
    op.add_column('pages', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('pages', sa.Column('llm_latency_ms', sa.Integer(), nullable=True))
    op.alter_column('pages', 'scale_detection_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Method used to detect scale: vision_llm, ocr_predetected, ocr_pattern_match, manual_calibration, scale_bar',
               existing_nullable=True)
    op.drop_index('idx_pages_ocr_text_search', table_name='pages', postgresql_using='gin')
    op.drop_index('idx_pages_ocr_text_trgm', table_name='pages', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_pages_ocr_text_trgm', 'pages', ['ocr_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_pages_ocr_text_search', 'pages', [sa.text("to_tsvector('english'::regconfig, COALESCE(ocr_text, ''::text))")], unique=False, postgresql_using='gin')
    op.alter_column('pages', 'scale_detection_method',
               existing_type=sa.VARCHAR(length=50),
               comment='Method used to detect scale: vision_llm, ocr_predetected, ocr_pattern_match, manual_calibration, scale_bar',
               existing_nullable=True)
    op.drop_column('pages', 'llm_latency_ms')
    op.drop_column('pages', 'llm_provider')
    op.drop_column('pages', 'description')
    op.drop_column('pages', 'concrete_elements')
    op.drop_column('pages', 'page_type_confidence')
    op.drop_column('pages', 'page_type')
    op.drop_column('pages', 'discipline_confidence')
    op.drop_column('pages', 'discipline')
    op.create_index('ix_classification_history_status', 'classification_history', ['status'], unique=False)
    op.create_index('ix_classification_history_provider_model', 'classification_history', ['llm_provider', 'llm_model'], unique=False)
    op.create_index('ix_classification_history_created_at', 'classification_history', ['created_at'], unique=False)
    # ### end Alembic commands ###
